### ISSUE TITLE
[Feature Request] support path rename in custom view

### ISSUE THREAD

**Issue by ixzh** [vifm/vifm#956] opened 2023-11-15 05:06 UTC
I quote:
> operations that use files of a custom view as a source (e.g. yanking, copying, moving file from custom view, deletion) and operations that modify names are all allowed.

Currently I can only change file names. Would it be possible to support path?  Namely, modify the paths, and upon save, the files, line by line, are moved to the new path (and create folders along the way if necessary)

say I have the following custom view by `:find jpg` then press `b`:
```
1/covers/001.jpg
1/covers/002.jpg
```
I would like to do a `cw` on all, which becomes:
```
1 covers 001.jpg
1 covers 002.jpg
```
upon save, I got :
<img width="628" alt="image" src="https://github.com/vifm/vifm/assets/14981695/2aaf121d-8537-4132-90b8-9007edf835eb">

It would be great to have custom view rename combined with the power of vim.

**Comment by xaizek** [comment] 2023-11-15 13:37
I'll close this because it's a duplicate of #147, please subscribe to that issue.

By the way, it's not really custom-view specific, `:rename!` also doesn't move files, although custom views might in fact need some special handling.

**Closed by xaizek** 2023-11-15 13:37 UTC

**Comment by ixzh** [comment] 2023-11-15 16:15
noted!
