### ISSUE TITLE
Two lines in status line

### ISSUE THREAD

**Issue by jcarreja** [vifm/vifm#549] opened 2020-05-15 11:08 UTC
Is it possible to have two lines in the status line?

**Comment by xaizek** [comment] 2020-05-15 11:31
Duplicate of #492

**Comment by xaizek** [comment] 2020-05-15 11:32
No, this needs to be implemented.

**Comment by xaizek** [comment] 2021-05-13 20:41
Added `%N` macro that adds line break to statusline, so it's possible now.

**Closed by xaizek** 2021-05-13 20:41 UTC
Labels: duplicate
