### ISSUE TITLE
make fails on macos

### ISSUE THREAD

**Issue by dirkroorda** [vifm/vifm#958] opened 2023-11-19 20:04 UTC
There is no clear way to install it on macos (14.1.1).

Downloading from source and then ./configure, make, make install fails in the make step.

```
In file included from int/term_title.c:24:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:728:17: error: expected parameter declarator
__OSX_AVAILABLE(14.0) __IOS_AVAILABLE(17.0) __WATCHOS_AVAILABLE(10.0)
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:728:17: error: expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:728:16: note: to match this '('
__OSX_AVAILABLE(14.0) __IOS_AVAILABLE(17.0) __WATCHOS_AVAILABLE(10.0)
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:728:23: error: expected function body after function declarator
__OSX_AVAILABLE(14.0) __IOS_AVAILABLE(17.0) __WATCHOS_AVAILABLE(10.0)
                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:759:17: error: expected parameter declarator
__OSX_AVAILABLE(14.0) __IOS_AVAILABLE(17.0) __WATCHOS_AVAILABLE(10.0)
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:759:17: error: expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:759:16: note: to match this '('
__OSX_AVAILABLE(14.0) __IOS_AVAILABLE(17.0) __WATCHOS_AVAILABLE(10.0)
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/term.h:759:23: error: expected function body after function declarator
__OSX_AVAILABLE(14.0) __IOS_AVAILABLE(17.0) __WATCHOS_AVAILABLE(10.0)
                      ^
6 errors generated.
make[1]: *** [int/term_title.o] Error 1
make: *** [all-recursive] Error 1
```

When I go to GitHub, I see an `INSTALL` file with some hints to install it on macos:

```
Get and install libscursesw or libncursesw.
```

But brew install fails for both of them.

In 2011 this was already an
[issue](https://sourceforge.net/p/vifm/discussion/158927/thread/d7d6178a/).

Googling "libscursesw macos" reveals a rabbit hole, e.g.
[this](https://gist.github.com/cnruby/960344).

Guys, please give some decent install procedure to install this on a modern mac, if possible.

**Comment by dirkroorda** [comment] 2023-11-19 20:14
Update: when I clone the repo then the procedure ./configure make make install does not throw errors.

And the vifm command works.

So on macos the installation instructions could be

1. open a terminal
2. do `git clone https://github.com/vifm/vifm`
3. cd to the inner `vifm` directory
4. give the following sequence of commands:
5. `./configure`
6. `make`
7. `make install`
8. Installation is complete.

Start the app by giving the command (in a terminal)

`vifm`

**Comment by xaizek** [comment] 2023-11-19 22:27
Vifm is [in Homebrew](https://formulae.brew.sh/formula/vifm), I guess that's the easiest way on OS X.

This compilation failure didn't apper until 14.1. The fix is in 6a05ff9. And this issue is a duplicate of #955.

**Closed by xaizek** 2023-11-19 22:27 UTC

**Comment by dirkroorda** [comment] 2023-11-24 11:47
Indeed,

```
brew install vifm
```

works nicely.

It would be very helpful if:

In the readme there is a section about installation.

And in that section you mention `brew install vifm` as the best way to install vifm.
Something like this:

### macos

Install via [HomeBrew](https://brew.sh)

Then

```
brew install vifm
```

That will save macos users quite a bit of trouble.

**Comment by dirkroorda** [comment] 2023-11-24 19:59
But in practice there is always a method that requires the least special knowledge. If you advertize that, then many users will be thankful. Those that prefer other methods tend to know what they are doing.

**Comment by xaizek** [comment] 2023-11-24 22:51
You have a point, I'll consider mentioning some installation instructions.
