### ISSUE TITLE
Corrupted double-linked list. Core dumped

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#491] opened 2019-11-03 20:00 UTC
Hi!

I used this shortcut to edit my vifmrc:

    nnoremap <space>c :write | edit $MYVIFMRC | restart<cr>

After I closed Vim (`:x`) I returned to Vifm. It was unresponsive and had this message at the bottom:

>corrupted double-linked list. Aborted core dumped

journalctl shows this:

    Nov 03 20:46:56 zurich systemd-coredump[2902269]: Process 2871346 (vifm) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 2871346:
                                                      #0  0x00007fbb48551f25 raise (libc.so.6)
                                                      #1  0x00007fbb4853b897 abort (libc.so.6)
                                                      #2  0x00007fbb48595258 __libc_message (libc.so.6)
                                                      #3  0x00007fbb4859c77a malloc_printerr (libc.so.6)
                                                      #4  0x00007fbb4859cfec unlink_chunk.isra.0 (libc.so.6)
                                                      #5  0x00007fbb4859fc31 _int_malloc (libc.so.6)
                                                      #6  0x00007fbb485a0fc9 malloc (libc.so.6)
                                                      #7  0x00007fbb485ecf97 create_token_tree.isra.0 (libc.so.6)
                                                      #8  0x00007fbb485ed275 lower_subexp (libc.so.6)
                                                      #9  0x00007fbb485ed365 lower_subexps (libc.so.6)
                                                      #10 0x00007fbb485eb40a postorder (libc.so.6)
                                                      #11 0x00007fbb485f8cd5 re_compile_internal (libc.so.6)
                                                      #12 0x00007fbb485fa12e regcomp (libc.so.6)
                                                      #13 0x000055e472f5ffc3 n/a (vifm)
                                                      #14 0x000055e472f6104a n/a (vifm)
                                                      #15 0x000055e472f72057 n/a (vifm)
                                                      #16 0x000055e472f24a74 n/a (vifm)
                                                      #17 0x000055e472f6e523 n/a (vifm)
                                                      #18 0x000055e472f6f68a n/a (vifm)
                                                      #19 0x000055e472f1ba6a n/a (vifm)
                                                      #20 0x000055e472f1bb73 n/a (vifm)
                                                      #21 0x000055e472f1bbf8 n/a (vifm)
                                                      #22 0x000055e472fa31ff n/a (vifm)
                                                      #23 0x000055e472f70d6a n/a (vifm)
                                                      #24 0x000055e472f24a74 n/a (vifm)
                                                      #25 0x000055e472f6e523 n/a (vifm)
                                                      #26 0x000055e472f6f68a n/a (vifm)
                                                      #27 0x000055e472f405ec n/a (vifm)
                                                      #28 0x000055e472f25e47 n/a (vifm)
                                                      #29 0x000055e472f2648c n/a (vifm)
                                                      #30 0x000055e472f269d8 n/a (vifm)
                                                      #31 0x000055e472f26fb4 n/a (vifm)
                                                      #32 0x000055e472f27138 n/a (vifm)
                                                      #33 0x000055e472f27252 n/a (vifm)
                                                      #34 0x000055e472f272bf n/a (vifm)
                                                      #35 0x000055e472f272bf n/a (vifm)
                                                      #36 0x000055e472f272bf n/a (vifm)
                                                      #37 0x000055e472f272bf n/a (vifm)
                                                      #38 0x000055e472f272bf n/a (vifm)
                                                      #39 0x000055e472f272bf n/a (vifm)
                                                      #40 0x000055e472f272bf n/a (vifm)
                                                      #41 0x000055e472f272bf n/a (vifm)
                                                      #42 0x000055e472f272bf n/a (vifm)
                                                      #43 0x000055e472f272bf n/a (vifm)
                                                      #44 0x000055e472f272bf n/a (vifm)
                                                      #45 0x000055e472f272bf n/a (vifm)
                                                      #46 0x000055e472f272bf n/a (vifm)
                                                      #47 0x000055e472f272bf n/a (vifm)
                                                      #48 0x000055e472f272bf n/a (vifm)
                                                      #49 0x000055e472f272bf n/a (vifm)
                                                      #50 0x000055e472f272bf n/a (vifm)
                                                      #51 0x000055e472f272bf n/a (vifm)
                                                      #52 0x000055e472f272bf n/a (vifm)
                                                      #53 0x000055e472f272bf n/a (vifm)
                                                      #54 0x000055e472f272bf n/a (vifm)
                                                      #55 0x000055e472f272bf n/a (vifm)
                                                      #56 0x000055e472f272bf n/a (vifm)
                                                      #57 0x000055e472f272bf n/a (vifm)
                                                      #58 0x000055e472f272bf n/a (vifm)
                                                      #59 0x000055e472f272bf n/a (vifm)
                                                      #60 0x000055e472f272bf n/a (vifm)
                                                      #61 0x000055e472f272bf n/a (vifm)
                                                      #62 0x000055e472f272bf n/a (vifm)
                                                      #63 0x000055e472f272bf n/a (vifm)
                                                      
                                                      Stack trace of thread 2871347:
                                                      #0  0x00007fbb486ecc45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                      #1  0x000055e472f69070 n/a (vifm)
                                                      #2  0x00007fbb486e64cf start_thread (libpthread.so.0)
                                                      #3  0x00007fbb486152d3 __clone (libc.so.6)

This *does not* happen every time I use the shortcut.

Here's my vifmrc:

    " vim: filetype=vifm :

    " Use :reload in vifm to reload the configuration file

    " Other config files:
    " https://github.com/Jenyay/vifmrc
    " https://github.com/onovy/vifmrc
    " https://github.com/valsorym/vifmrc
    " https://github.com/dmarov/vifmrc
    " https://github.com/rusito-23/vifm-powerline

    " See also:
    " https://vifm.info/manual.shtml
    " https://wiki.archlinux.org/index.php/Vifm

    " This is the actual command used to start vi. The default is vim.
    set vicmd=vim

    " This makes vifm perform file operations on its own instead of relying on
    " standard utilities like `cp`.  While using `cp` and alike is a more universal
    " solution, it's also much slower when processing large amounts of files and
    " doesn't support progress measuring.
    set syscalls

    " Trash Directory
    " The default is to move files that are deleted with dd or :d to
    " the trash directory.  If you change this you will not be able to move
    " files by deleting them and then using p to put the file in the new location.
    " I recommend not changing this until you are familiar with vifm.
    " This probably shouldn't be an option.
    set trash

    " This is how many directories to store in the directory history.
    set history=100

    " Automatically resolve symbolic links on l or Enter.
    set nofollowlinks

    " With this option turned on you can run partially entered commands with
    " unambiguous beginning using :! (e.g. :!Te instead of :!Terminal or :!Te<tab>).
    " set fastrun

    " Natural sort of (version) numbers within text.
    set sortnumbers

    " Maximum number of changes that can be undone.
    set undolevels=100

    " If you installed the vim.txt help file set vimhelp.
    " If you would rather use a plain text help file set novimhelp.
    set novimhelp

    " If you would like to run an executable file when you
    " press return on the file name set this.
    set norunexec

    " Selected color scheme

    colorscheme Zurich

    " Format for displaying time in file list. For example:
    " TIME_STAMP_FORMAT=%m/%d-%H:%M
    " See man date or man strftime for details.

    set timefmt=%y/%m/%d\ %H:%M

    " Show list of matches on tab completion in command-line mode

    set wildmenu

    " Display completions in a form of popup with descriptions of the matches

    set wildstyle=popup

    " Display suggestions in normal, visual and view modes for keys, marks and
    " registers (at most 5 files).  In other view, when available.
    set suggestoptions=normal,visual,view,otherpane,keys,marks,registers

    " Ignore case in search patterns unless it contains at least one uppercase
    " letter
    set ignorecase
    set smartcase

    " Don't highlight search results automatically
    set nohlsearch

    " Use increment searching (search while typing)
    set incsearch

    " Try to leave some space from cursor to upper/lower border in lists

    set scrolloff=4

    " Don't do too many requests to slow file systems
    if !has('win')
        set slowfs=curlftpfs
    endif

    " Defines how we display time.
    " The status line uses it to show last modified date of the current file
    set timefmt="%Y-%m-%d %H:%M:%S"

    " Use kibibytes (1024 bits), mebibytes (1024 kibiytes), gibibytes (1024 mebibytes) and so forth
    set sizefmt=units:iec,precision:2

    " Use KiB, MiB, GiB instead of K, M, G
    set iec

    " Sets the window title to the vifm's current directory
    set title

    " Set custom status line look
    " See 'statusline' in man vifm
    " %s size of current file
    " %E the total size of selected files
    " %1 applies User1 color
    " %u user who owns the file
    " %g group the file belongs to
    " %d file modification date
    " %= right-aligns the rest of the fields
    " %{} execute an expressions. For example, this prints the contents of the file currently under the cursor:
    " %{system('cat ' . expand('%c'))}
    " See also:
    "  * https://vifm.info/manual.shtml#Expression%20syntax
    "  * https://vifm.info/manual.shtml#Functions
    "
    " Have a look here for colors:
    " https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
    highlight User1 ctermbg=none ctermfg=none cterm=none
    highlight User2 ctermbg=none ctermfg=none cterm=reverse
    " This shows the extended attributes for files (and the number of files in a directory) but it creates lag when browsing files
    "%{system('~/config/shell_conf/.config/vifm/file_info.sh ' . expand('%c'))}
    " Gets file under cursor (see command macros): %{expand('%c')}

    " See this for ideas on how to speed this up:
    " https://github.com/vifm/vifm/issues/436
    "set statusline="%1*%A %2* %u:%g %1* %10E %2* 👉 %d %1* %{system('~/config/shell_conf/.config/vifm/file_info.sh ' . expand('%c'))}%=💽 %a"
    set statusline="%1*%A %2* %u:%g %1* %E %=💽 %a"

    """"""""""" Command mappings. See also https://vifm.info/manual.shtml#Commands """"""""""""""""
    """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

    " :com[mand][!] command_name action
    " The following macros can be used in a command
    " %a is replaced with the user arguments.
    " %c the current file under the cursor.
    " %C the current file under the cursor in the other directory.
    " %f the current selected file, or files.
    " %F the current selected file, or files in the other directory.
    " %b same as %f %F.
    " %d the current directory name.
    " %D the other window directory name.
    " %m run the command in a menu window

    command! df df -h %m 2> /dev/null
    command! diff vim -d %f %F
    command! zip zip -r %f.zip %f
    command! run !! ./%f
    command! make !!make %a
    command! mkcd :mkdir %a | cd %a
    command! vgrep vim "+grep %a"
    command! reload :write | restart

    " Command to change directory by picking it via FZF, %a is a parameter
    " From https://github.com/vifm/vifm/issues/482
    command! fzfcd :execute 'cd' fnameescape(term('fd --type d --hidden --exclude .git --full-path %a | fzf 2> /dev/tty'))

    " TODO: Use xdg-open to open a fuzzy selected file in the current directory
    " or below

    " This only works every second time
    "nnoremap <space>T :fzfcd ~/text/<cr>
    nnoremap <a-t> :fzfcd ~/text/<cr>
    nnoremap <a-c> :fzfcd ~/config/<cr>
    " Search in the current directory
    nnoremap <a-h> :fzfcd .<cr>

    " Start shell in current directory, replacing vifm window
    nnoremap s :shell<cr>

    " Toggle horizontal window splitting
    nnoremap <space>o :split!<cr>

    " Open console in current directory in a new window. Don't display error message in vifm
    nnoremap <space>t :!termite 2>/dev/null &<cr>

    " Display sorting dialog
    nnoremap S :sort<cr>

    " Toggle visibility of preview window
    nnoremap w :view<cr>
    vnoremap w :view<cr>gv

    nnoremap <space>q :quit<cr>

    " Open editor to edit vifmrc and apply settings after returning to vifm
    nnoremap <space>c :write | edit $MYVIFMRC | restart<cr>

    " Reload configuration
    nnoremap <space>r :reload<cr>

    " Go backward and forward through directory history
    nnoremap <c-h> :histprev<cr>
    nnoremap <c-l> :histnext<cr>

    " Toggle whether to wrap lines in the preview panel
    nnoremap <space>w :set wrap!<cr>

    " Yank current directory path into the clipboard
    nnoremap yd :!echo %d | wl-copy %i<cr>

    " Yank current file path into the clipboard
    nnoremap yf :!echo %c:p | wl-copy %i<cr>

    " yank current file name without path into the clipboard
    nnoremap yn :!echo -n %c | wl-copy %i<cr>

    """""""""""""""" Filetype association""""""""""""""""""""""
    """""""""""""""""""""""""""""""""""""""""""""""""""""""""""

    " The file type is for the default programs to be used with
    " a file extension.
    " :filetype pattern1,pattern2 defaultprogram,program2
    " :fileviewer pattern1,pattern2 consoleviewer
    " The other programs for the file type can be accessed with the :file command
    " The command macros %f, %F, %d, %F may be used in the commands.
    " The %a macro is ignored.  To use a % you must put %%.

    " For automated FUSE mounts, you must register an extension with :file[x]type
    " in one of following formats:
    "
    " :filetype extensions FUSE_MOUNT|some_mount_command using %SOURCE_FILE and %DESTINATION_DIR variables
    " %SOURCE_FILE and %DESTINATION_DIR are filled in by vifm at runtime.
    " A sample line might look like this:
    " :filetype *.zip,*.jar,*.war,*.ear FUSE_MOUNT|fuse-zip %SOURCE_FILE %DESTINATION_DIR
    "
    " :filetype extensions FUSE_MOUNT2|some_mount_command using %PARAM and %DESTINATION_DIR variables
    " %PARAM and %DESTINATION_DIR are filled in by vifm at runtime.
    " A sample line might look like this:
    " :filetype *.ssh FUSE_MOUNT2|sshfs %PARAM %DESTINATION_DIR
    " %PARAM value is filled from the first line of file (whole line).
    " Example first line for SshMount filetype: root@127.0.0.1:/
    "
    " You can also add %CLEAR if you want to clear screen before running FUSE
    " program.

    " PDF, PostScript, DJVU, comic books
    filetype *.pdf,*.djvu,*.ps,*.cbr,*.eps,*.ps.gz zathura %c %i &
    fileviewer *.pdf pdftotext -nopgbrk %c -

    " E-books
    filetype *.epub calibre %f 2>/dev/null &

    " Images
    filetype *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.webp,*.xpm,*pbm,*ppm imv %f 2>/dev/null &
    fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.webp,*.xpm
            \ identify %f

    " Video and audio files
    filetype *.aac,*.anx,*.asf,*.au,*.avi,*.axa,*.flac,*.m2a,*.m4a,*.mid,*.midi,*.mp3,*.mpc,*.og[agx],*.opus,*.ra,*.ram,*.rm,*.spx,*.wav,*.wma,*.ac3,*.avi,*.mp4,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,*.fl[icv],*.m2v,*.mov,*.webm,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,*.as[fx] vlc %f 2>/dev/null &

    fileviewer *.flac,*og[agx],*.mp3,*.wav ffprobe %c 2>&1 | grep -A 20 "Input #0"

    fileviewer *.avi,*.mp4,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,
              \*.fl[icv],*.m2v,*.mov,*.webm,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,
              \*.as[fx]
            \ ffprobe -pretty %c 2>&1 | grep -A 20 "Input #0"

    " Man page
    filetype *.[1-8] man ./%c
    fileviewer *.[1-8] man ./%c | col -b

    " MD5
    filetype *.md5
          \ {Check MD5 hash sum}
          \ md5sum -c %f %S,

    " SHA1
    filetype *.sha1
          \ {Check SHA1 hash sum}
          \ sha1sum -c %f %S,

    " SHA256
    filetype *.sha256
          \ {Check SHA256 hash sum}
          \ sha256sum -c %f %S,

    " SHA512
    filetype *.sha512
          \ {Check SHA512 hash sum}
          \ sha512sum -c %f %S,

    " GPG signature
    filetype *.asc
          \ {Check signature}
          \ !!gpg --verify %c,

    " Torrent
    filetype *.torrent transmission-gtk %f &
    fileviewer *.torrent dumptorrent -v %c

    " Archives
    " 7z -ba prints the files inside the archive with their creation date and size. Column six is the file's name and we print everything after that. If we printed only the sixth column, the file name after its first space would be cut off
    fileviewer *.tgz,*.tar.gz,*.tar.bz2,*.tbz2,*.tar.txz,*.txz,*.tar,*.rar,*.7z,*.zip,*.jar,*.war,*.ear,*.oxt 7z -ba l %c | awk '{ s = ""; for (i = 6; i <= NF; i++) s = s $i " "; print s }'

    " Office files
    filextype *.odt,*.doc,*.docx,*.xls,*.xlsx,*.odp,*ods,*.ppt,*.pptx,*.numbers,*.pages libreoffice %f &
    fileviewer *.doc catdoc %c
    fileviewer *.docx docx2txt.pl %f -

    " Directories
    filextype */
            \ tree %f &,

    " Syntax highlighting in preview
    "
    " Explicitly set highlight type for some extensions
    "
    " 256-color terminal
    " fileviewer *.[ch],*.[ch]pp highlight -O xterm256 -s dante --syntax c %c
    " fileviewer Makefile,Makefile.* highlight -O xterm256 -s dante --syntax make %c
    "
    " 16-color terminal
    " fileviewer *.c,*.h highlight -O ansi -s dante %c
    "
    " Or leave it for automatic detection
    "
    " fileviewer *[^/] pygmentize -O style=monokai -f console256 -g

    " Displaying pictures in terminal
    "
    " fileviewer *.jpg,*.png shellpic %c

    " What should be saved automatically between vifm runs
    set vifminfo=dhistory,savedirs,chistory,state,tui,shistory,
        \phistory,fhistory,dirstack,registers,bookmarks,bmarks

    " Examples of configuring both panels

    " Customize view columns a bit (enable ellipsis for truncated file names)
    "
    " set viewcolumns=-{name}..,6{}.

    " Filter-out build and temporary files
    "
    " filter! /^.*\.(lo|o|d|class|py[co])$|.*~$/

    " Various customization examples

    " Use ag (the silver searcher) instead of grep
    "
    " set grepprg='ag --line-numbers %i %a %s'

    " Add additional place to look for executables
    "
    " let $PATH = $HOME.'/bin/fuse:'.$PATH

    " Block particular shortcut
    "
    nnoremap <space> <nop>

    " Export IPC name of current instance as environment variable and use it to
    " communicate with the instance later.
    "
    " It can be used in some shell script that gets run from inside vifm, for
    " example, like this:
    "     vifm --server-name "$VIFM_SERVER_NAME" --remote +"cd '$PWD'"
    "
    " let $VIFM_SERVER_NAME = v:servername

    " From https://q2a.vifm.info/269/how-to-add-icons
    " 'reg' stands for regular files
    " ▶️
    set classify='📁 :dir:/,🤖 :exe:,:reg:,➡️  :link:'

    " Images
    " 🖼️
    " 🖼
    " 🎨
    set classify+='🎨 ::*.bmp,,*.gif,,*.jpeg,,*.jpg,,*.ico,,*.png,,*.webp,,*.ppm,,*.svg,,*.svgz,,*.tga,,*.tif,,*.tiff,,*.xbm,,*.xcf,,*.xpm,,*.xspf,,*.xwd::'

    " Videos
    "https://emojipedia.org/film-projector/
    " 🎥
    " 📽️
    " 🎬
    " 🍿
    set classify+='🍿 ::*.avi,,*.ts,,*.axv,,*.divx,,*.m2v,,*.m4p,,*.m4v,,*.mka,,*.mkv,,*.mov,,*.mp4,,*.flv,,*.mp4v,,*.mpeg,,*.mpg,,*.nuv,,*.ogv,,*.pbm,,*.pgm,,*.qt,,*.vob,,*webm,,*.wmv,,*.xvid::'

    " Audio
    set classify+='🎵 ::*.aac,,*.anx,,*.asf,,*.au,,*.axa,,*.flac,,*.m2a,,*.m4a,,*.mid,,*.midi,,*.mp3,,*.mpc,,*.oga,,*.ogg,,*.ogx,,*.ra,,*.ram,,*.rm,,*.spx,,*.wav,,*.wma,,*.ac3::'

    " Archives
    set classify+='📦 ::*.7z,,*.ace,,*.arj,,*.bz2,,*.cpio,,*.deb,,*.dz,,*.gz,,*.jar,,*.lzh,,*.lzma,,*.rar,,*.rpm,,*.rz,,*.tar,,*.taz,,*.tb2,,*.tbz,,*.tbz2,,*.tgz,,*.tlz,,*.trz,,*.txz,,*.tz,,*.tz2,,*.xz,,*.z,,*.zip,,*.zoo::'

---

Arch Linux 5.3.7.

Vifm is version: 0.10.1.

sway version is 1.2.

Thanks!

**Comment by xaizek** [comment] 2019-11-10 13:42
Hello!

Thanks for the report.

However, `corrupted double-linked list` occurs when glibc detects broken heap after the fact, so it's very likely that the issue was caused by your activity within the session rather than by `<space>c` shortcut. I don't see memory issues while using the mapping, which sort of confirms that (contents of `vifminfo` probably isn't to blame as well, since you can't reproduce the crash either). This might take another case of crash to track it down.

> ```vim
> " See this for ideas on how to speed this up:
> " https://github.com/vifm/vifm/issues/436
> "set statusline="%1*%A %2* %u:%g %1* %10E %2* 👉 %d %1* %{system('~/config/shell_conf/.config/vifm/file_info.sh ' . expand('%c'))}%=💽 %a"
> set statusline="%1*%A %2* %u:%g %1* %E %=💽 %a"
> ```

You can already use `extcached()` in 0.10.1.

**Comment by mb720** [comment] 2019-11-10 14:37
Interesting! 👍

>caused by your activity within the session

What could I have possibly done to break the heap?

**Comment by xaizek** [comment] 2019-11-10 17:09
It could be pretty much any operation or a sequence of operations, possibly combined with specific list of files. There is a bug somewhere, but the crash like that only says that it exists. Guessing won't be very productive, but if it happens again you might try to recall what you were doing before the crash (if it's not `<space>c`, it should be something earlier than that).

**Comment by xaizek** [comment] 2020-10-29 17:58
Looks like there were no more instances of this crash in a year, so I'll close this.

There was one memory related crash fixed in v0.11 in https://github.com/vifm/vifm/commit/fea547cc08aace94105bae46e26984bd22e7f8dd. This might be it if you used tabs when it happened, since histories are resized several times during `:restart`.

**Closed by xaizek** 2020-10-29 17:58 UTC
Labels: bug
