### ISSUE TITLE
Colors change when reloading config

### ISSUE THREAD

**Issue by Cyfell** [vifm/vifm#557] opened 2020-06-11 15:54 UTC
Hi all,
I just fresh installed vifm. (loving it already)
I tried to modify the default config under $HOME/.config/vifm/vifmrc and reload by :restart command but each time it change the color of the unselected window:
before using :restart : 
![screenshot_2020-06-11_17-41-53_917412224](https://user-images.githubusercontent.com/12376020/84407449-2abf0180-ac0b-11ea-93fa-ea0cb7ff189b.png)

after using :restart : 
![screenshot_2020-06-11_17-42-16_763092912](https://user-images.githubusercontent.com/12376020/84408529-8e95fa00-ac0c-11ea-9a02-8f2cb95a0b07.png)

even when id dont modify my config file and just :restart vifm this behaviour shows up.
i tried uninstall/install but it doesn't change a thing.
if i remove my config folder ($HOME/.config/vifm/vifmrc) and call vifm it seams to relad the default config and color scheme come back to normal.

have you experienced that ?

OS: Arch Linux x86_64
Shell: bash 5.0.17
WM: sway (wayland)
Terminal: tilix
vifm: 0.10.1

**Comment by xaizek** [comment] 2020-06-11 16:41
Duplicate of #532

**Comment by xaizek** [comment] 2020-06-11 16:45
Thanks for the report. It's already fixed in c3c58abccf3f08d3edcdcbe97f8ce1ebb450a2b2.

The problem is caused by `cterm=bold,underline,reverse,standout,italic` in default color scheme that's written on first startup. Just remove that part of the line where it appears in `$VIFM/colors/Default.vifm` (do `:e $VIFM/colors/Default.vifm` inside vifm).

**Closed by xaizek** 2020-06-11 16:45 UTC
Labels: bug, duplicate, ui

**Comment by Cyfell** [comment] 2020-06-11 16:47
Thanks for this amazing work !
