### ISSUE TITLE
Feature: nicer tree view

### ISSUE THREAD

**Issue by nobodyatandnothing** [vifm/vifm#783] opened 2022-03-29 07:08 UTC
use '│, ─, └, ├, ' instead of '|, -, `-, |-,'

reference: https://en.wikipedia.org/wiki/Box-drawing_character

**Comment by PRESFIL** [comment] 2022-03-29 09:20
Does this require pre-installed fonts that support these characters? On Windows It will cause trouble, definitely ;)

**Comment by xaizek** [comment] 2022-03-29 11:54
Duplicate of #716, see my answer there.

**Closed** 2022-03-29 11:54 UTC

**Comment by xaizek** [comment] 2022-03-29 11:56
> Does this require pre-installed fonts that support these characters? On Windows It will cause trouble, definitely ;)

It should depend on `u` in `'tuioptions'` and user should determine whether it can work.
