### ISSUE TITLE
[Bug] vifm has SegFault on startup on new MacOS Sequoia

### ISSUE THREAD

**Issue by niklas-tag24** [vifm/vifm#1021] opened 2024-09-17 10:44 UTC
Hi.

I have the latest macOS (15.0 Sequoia) and installed vifm with `brew install vifm`. Everytime I try to open it with `vifm`, It immediatelly crashes with:

`   [1]    11613 segmentation fault  vifm`

I tried openning it with iTerm, with Alacritty, with and without tmux.

**Comment by xaizek** [comment] 2024-09-17 12:11
Hi.

Will need to see if I can run new macOS in a VM to investigate.

**Comment by niklas-tag24** [comment] 2024-09-17 12:27
Thanks :) If it is important, the `vifm --version` returns

Version: 0.13
Git info: built out of repository
Compiled at: Apr  4 2023 20:42:50

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution

**Comment by VadimCurca** [comment] 2024-09-22 09:29
@niklas-tag24 I encountered the same issue, which was fixed by reinstalling the latest vifm from the source. See the instructions in [./INSTALL](https://github.com/vifm/vifm/blob/master/INSTALL). In short, I built with `./configure && sudo make install`.
The latest official release is quite outdated, and there have been many fixes and added features since then.

**Comment by xaizek** [comment] 2024-09-22 10:29
I don't remember any fixes for Mac OS, so maybe building v0.13 from source will work too.  I didn't suggest that because I think that's what `brew` is doing anyway, but there could be differences in build environment.

**Comment by mhz-tamb** [comment] 2024-09-25 10:07
I encountered the same problem after updating MacOS to 15.0 Sequoia. Reinstalling vifm via brew helped: `brew reinstall vifm`.

**Comment by xaizek** [comment] 2024-09-29 12:59
@niklas-tag24, was it an update of MacOS or fresh installation?  Update might require re-installation of programs so they don't try to use libraries which are no longer there.  I tried it and can't reproduce the failure with either `brew install vifm` or when building v0.13 or master versions from sources.

**Comment by AeroCross** [comment] 2024-10-03 00:27
Can confirm that reinstalling (`brew reinstall vifm`) fixed the segfault for me as well.

**Comment by xaizek** [comment] 2024-10-03 17:34
Thanks to everyone for commenting.  From what I can tell, it's a local issue that can't be addressed in the code.  If there are reasons to believe otherwise, please comment.

I'll close this, but will pin the issue for some months, so it's easier to find as people update their systems.

**Closed by xaizek** 2024-10-03 17:34 UTC
Labels: osx
