### ISSUE TITLE
Memory overflow with image/video previews

### ISSUE THREAD

**Issue by iboggs** [vifm/vifm#907] opened 2023-06-02 05:58 UTC
I've managed to get image and video previews working well on my setup, with one major except: direct color. While direct color works, it quickly becomes apparent that it runs against a wall (presumably memory limitations) after a few previews have been loaded. 

Assuming the previews were using too much memory, I attempted to use the `%pu` command so that it wouldn't be cached after the user moves to another item. If that is the intended functionality of `%pu`, I was unable to get it to work properly.

Is there anything I can do to clear the preview from the cache?

Attached is an example of what the corruption caused by this looks like.
![corrupted](https://github.com/vifm/vifm/assets/121784366/15f3e5fa-141e-43bf-9605-24548f3eb28f)

**Comment by xaizek** [comment] 2023-06-02 11:45
I don't think it has anything to do with cache or memory.  The only effect from a too large amount of data is that it wouldn't be cached.

The image suggests that you hit a limitation of a number of color pairs (combination of foreground and background colors).  If you open `:version` menu, information in the 2 bottom paragraphs should be helpful, please post it here (you can save it to a file with `:write ~/vifm-version`).

**Comment by xaizek** [comment] 2023-06-03 09:13
```
Terminal name: st-direct
Max colors: 16777216
Max color pairs: 65536
Extended colors: present
RGB: 1
Direct color: yes

Preview cache size: 1.2 M
```
This looks fine.  Exhausting 65536 pairs would take about 256x256 image with all characters being different.  I tried opening images in `st` with `chafa -c full -s %pw %c` and can't reproduce the issue.  What image converter are you using?

**Comment by xaizek** [comment] 2023-06-04 11:53
> I should note, this only seems to happen after I've loaded ten or so images. Could curses be handling the pairs strangely?

It might be a bug in Vifm.  I would just expect it to manifest consistently.  The only thing I get is a segfault that seems to happen inside curses on drawing.  And there is also a slowdown after opening many images (probably pair lookup is slow).  What's your version of ncurses?  I want to try building with it.  Mine is 6.3.

**Comment by itshog** [comment] 2023-06-26 22:25
I have the exact same problem when setting the `TERM` variable to the `-direct` variant of my terminal (foot) and using chafa with full color mode. The problem doesn't seem to occur when using the 240 color mode of chafa.

> **Edit:** could you try with AppImage from https://github.com/vifm/vifm/releases/tag/v0.13? That one has ncurses v6.4 and it behaves like v6.3 for me. Could be helpful to compare with the behaviour on your side as this unifies binary and most of its depenencies including terminal database.

I tried the AppImage mentioned here, and the problem persist but in a different manner: instead of slowly becoming more corrupted, images show fine until the program crashes, leaving the terminal in a mangled state (almost like when dumping a binary file to stdout).

I'm attaching the crash log found with journalctl:

```
Started Process Core Dump (PID 162634/UID 0).
Could not parse number of program headers from core file: invalid `Elf' handle
Module /tmp/.mount_vifm-vIpVw1R/usr/bin/vifm without build-id.
Module /tmp/.mount_vifm-vIpVw1R/usr/bin/vifm
Stack trace of thread 162176:
#0  0x00000000004dcd34 n/a (/tmp/.mount_vifm-vIpVw1R/usr/bin/vifm + 0xdcd34)
ELF object binary architecture: AMD x86-64
```

I need to verify this, but it seems that (as for the problem mentioned earlier) this crash doesn't happen when using 240 color mode in chafa

**Comment by xaizek** [comment] 2023-06-27 17:04
> I tried the AppImage mentioned here, and the problem persist but in a different manner: instead of slowly becoming more corrupted, images show fine until the program crashes, leaving the terminal in a mangled state (almost like when dumping a binary file to stdout).

Thanks, the issue sounds similar to what I get and it might be the same in all these cases.

It looks like while "Max color pairs" is 65536, ncurses can't handle more than 32767. Non-extended API has this ceiling due to the use of `short int` which becomes negative after that and I suspect that `short int` is still in use somewhere in ncurses sources resulting in things breaking down.

Limiting available color pairs in the code fixes the crash, but the same effect can be achieved by editing terminfo entry as a workaround.

**Comment by itshog** [comment] 2023-06-27 19:25
> Limiting available color pairs in the code fixes the crash, but the same effect can be achieved by editing terminfo entry as a workaround.

Thanks for the fast response! I'm a bit confused though: is the problem solvable by Vifm or is it up to the underlying ncurses library to fix the bug? Should we report it to upstream ncurses? And what about the workaround you mentioned, can it be applied by the end user?

**Comment by xaizek** [comment] 2023-06-27 20:54
> is the problem solvable by Vifm or is it up to the underlying ncurses library to fix the bug?

Workaround is possible, but the bug likely needs to be fixed in ncurses.

> Should we report it to upstream ncurses?

I first want to write a test app to expose the behaviour to make sure it's not related to Vifm.

> And what about the workaround you mentioned, can it be applied by the end user?

See https://github.com/vifm/vifm.vim/issues/88#issuecomment-1510426481, but use something like:
```
foot-direct| foot-direct with ncurses pairs workaround,
	use=foot-direct, pairs#0x8000
```
This should half the number of available color pairs.

**Comment by itshog** [comment] 2023-06-28 07:39
> See [vifm/vifm.vim#88 (comment)](https://github.com/vifm/vifm.vim/issues/88#issuecomment-1510426481), but use something like:
> 
> ```
> foot-direct| foot-direct with ncurses pairs workaround,
> 	use=foot-direct, pairs#0x8000
> ```
> 
> This should half the number of available color pairs.

Thanks, this works like a charm! I tested with a large image directory (about 250 pictures) and I was able to get smooth truecolor preview with chafa, whereas before the bug would show after previewing consecutively 10 to 15 images.

> I first want to write a test app to expose the behaviour to make sure it's not related to Vifm.

If you need help with testing let me know, I'm not a developer but I'm willing to contribute.

**Comment by xaizek** [comment] 2023-06-29 12:15
ncurses doesn't have a bug, the way Vifm uses ncurses API limits it to 32768 color pairs and then values overflow causing a crash inside ncurses.  I might have asummed that greater values are impossible due to terminfo limitation, which seems to have been lifted now allowing for up to 65536 pair and causing this issue to manifest.  Or I've just missed/forgot to use the API right, who knows.

Anyhow, thanks to @iboggs and @itshog.  Will fix this.

**Comment by itshog** [comment] 2023-06-30 11:43
I'm glad this is gonna be fixed. On the side note: will this change also allow to use truecolor without manually setting the `TERM` variable to the `-direct` variant or is it unrelated?

Anyway, thanks for finding out the problem!

**Comment by xaizek** [comment] 2023-06-30 11:59
> On the side note: will this change also allow to use truecolor without manually setting the `TERM` variable to the `-direct` variant or is it unrelated?

No, it won't.  ncurses won't be able to use RGB if `$TERM` doesn't point to an entry that allows 24-bit color, which is usually named `*-direct`.

**Closed** 2023-07-01 21:59 UTC
Labels: bug, ui

**Comment by itshog** [comment] 2023-07-02 20:29
Thank you for fixing this!

**Comment by drazil100** [comment] 2024-09-15 03:45
I am also having this issue with image previews for a long time now and my issues actually result in a crash. The issue is persistent across multiple machines and reinstalls but I didn't always have issues. After years of occasionally running into this I decided to report it.

```
Version: 0.13
Git info: built out of repository
Compiled at: Jul 14 2024 01:22:23
```

My method of generating image previews actually relies on a different tool called chafa. Here is the exact command I use. 
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.xpm,*.gif
	\ chafa -c full --color-space din99d -w 9 -s %pwx%ph -d 0 %c || true

```

It works fine at first but after several dozen images it will inevitably crashes with `Segmentation fault (Core dumped)`.

I really want to continue using chafa because it frankly produces AMAZING image previews and I am prepared to just deal with crashing, but I suspect this crash is actually related to this issue due to the fact it never triggers right away, only if enough images have loaded, and the one time managed to get it to NOT crash, all the images were foreground and background colored after it screwed up.

Not sure if there is anything that can be done on either your end or my end but I am happy to dig into the core dump (with guidance as I don't exactly know how) if it will help.

**Comment by xaizek** [comment] 2024-09-15 09:21
@drazil100, sounds like the same issue.  To be sure that it's fixed you could [build latest version from sources](https://wiki.vifm.info/index.php/Obtaining_Vifm#From_sources) (doesn't have to be installed, can be run as `src/vifm` for a test) and try to reproduce the crash.

**Comment by drazil100** [comment] 2024-09-15 22:01
> @drazil100, sounds like the same issue. To be sure that it's fixed you could [build latest version from sources](https://wiki.vifm.info/index.php/Obtaining_Vifm#From_sources) (doesn't have to be installed, can be run as `src/vifm` for a test) and try to reproduce the crash.

Weird. No crash anymore. I am on Manjaro so I assumed that my package would be up to date given that Manjaro is arch based and src/vifm DOES have the same version number as the one in the arch repos. I assumed that since this issue was closed over half a year ago that if I was still having issues it wasn't fixed...

Let me know if you need me to investigate further. Happy to help in any way I can. For now though I guess I will just the self-compiled version.

**Comment by xaizek** [comment] 2024-09-16 09:27
v0.13 release or Manjaro's package doesn't have this fix.  The version number is updated at the time of release, so you've basically compiled v0.14.
