### ISSUE TITLE
qmap/qnoremap <Space> not working properly on mac

### ISSUE THREAD

**Issue by ijleesw** [vifm/vifm#529] opened 2020-03-23 18:09 UTC
I wanted to switch between normal mode and view mode with `<Space>`, but while nnoremap is working properly, qmap and qnoremap aren't.

The followings are my vifmrc and vifmrc/macos version:
```
" vifmrc
view            " preview mode
color zenburn

set hlsearch    " highlight result
set ic          " ignore case
set incsearch   " show result w/o <Enter>

noremap r cW    " rename except extension
noremap R cw    " rename all

nnoremap <Space> <S-Tab>
qnoremap <Space> q


" vifm version : 0.10.1
" macOS version : 10.15.3
```

When I press `<Space>` in view mode, vifm changes the directory pane like what `<Tab>` does. The problem still remains when I change `q` to `<S-Tab>`.

By substituting `qnoremap` to `qmap`, `<Space>` acts like `<nop>` in view mode. Still if I add `qmap w q`, then `w` acts like `q` in view mode.

Seems like qmap/qnoremap is doing something wrong with `<Space>`..

**Comment by xaizek** [comment] 2020-03-23 22:07
Tested on macOS 10.12 and couldn't reproduce the issue.

Have you checked what mapping ends up looking like after vifm has started? I.e., does it say `q` in the first line of `:qnoremap <space>` menu (you can't see the space on the left)? Is this your complete `vifmrc`?

**Comment by ijleesw** [comment] 2020-03-24 03:44
I confess that I omitted comments of the last two lines of `vifmrc`. The following is my complete last two lines:
```
nnoremap <Space> <S-Tab>    " Switch to view mode in normal mode
qnoremap <Space> q    " Switch to normal mode in view mode

" There is one <tab> between <S-Tab> and ".
```
I thought this is equivalent to a comment-omitted version, but it seems like they aren't. (`:qnoremap <space>` shows `q` followed by a whitespace and the comment.)
Vifm works correctly after removing whitespaces and comments.

Still there's something I cannot understand.
This is my conjecture - when I pressed `<Space>` in view mode, the key press was mapped to `q` followed by `<Tab>`. It explains `vifm` changing the directory pane.
But if that's the case, `<Space>` shouldn't have worked properly in normal mode too - `<S-Tab>` followed by `<Tab>` does not switch to view mode. It rather falls back to normal mode.

Could you kindly explain what happens with `vifmrc` setting above?

**Comment by xaizek** [comment] 2020-03-24 12:50
Are you sure tabulation is present? Does the `:nmap <space>` menu say:
```
             <s-tab><c-i>" Switch to view mode in normal mode
```
with `<c-i>` in it? For me, it doesn't work if `<c-i>` is there and works if there are spaces.

**Comment by ijleesw** [comment] 2020-03-24 13:17
Nope, there are only spaces. I thought it will act like tabulation because I pressed tab key during modification of `vifmrc`.

This is the simplest scenario:

### Case 1
Complete `vifmrc`:
```
view
qnoremap <space> q
```
`:qnoremap <space>`:
```
┌── Mappings for View mode ────────────────────────────────────────────────────────────┐
│             q                                                                        │
│                                                                                      │
│             scroll page down                                                         │
```
It works.

### Case 2
Complete `vifmrc`:
```
view
qnoremap <space> q  " This is comment
```
`:qnoremap <space>`:
```
┌── Mappings for View mode ────────────────────────────────────────────────────────────┐
│             q  " This is comment                                                     │
│                                                                                      │
│             scroll page down                                                         │
```
It does not work.

**Comment by xaizek** [comment] 2020-03-24 14:37
In this case everything works as expected given that you can't have trailing comments in a mapping command. You don't get a tabulation there, so you must have [`'expandtab'`](https://vimhelp.org/options.txt.html#%27expandtab%27) option set in Vim.

**Comment by ijleesw** [comment] 2020-03-25 05:13
Okay I get that there's nothing to do with tab in the above case. Then could you explain what happens internally when I have a trailing comment in a mapping command?

**Comment by xaizek** [comment] 2020-03-25 13:05
Actually it's something weird:
1. <kbd>q</kbd> - leaves view-mode
2. <kbd>space</kbd> - switches pane
3. <kbd>space</kbd> - switches pane
4. <kbd>" T</kbd> - aborts handling of the mapping
5. Looks up and processes original key (<kbd>space</kbd>) among builtin keys of current mode which is normal mode by now

That's not really how it's supposed to work.  Aborting isn't bad, but repeated processing of the input is.

**Comment by ijleesw** [comment] 2020-03-25 14:21
Well I think that makes sense. Step `5.` switches pane, which is the action of `space` in normal mode. There are total 3 pane switching after leaving view-mode, so the result is normal mode of the other pane. It's just like what I wrote in the issue -- "When I press <Space> in view mode, vifm changes the directory pane like what <Tab> does."

Looks like there's no problem now...👍

**Comment by xaizek** [comment] 2020-03-30 14:27
> Any further plan for the modification of the behavior?

Yes, at least this part should be fixed.

**Closed** 2020-04-25 13:05 UTC
Labels: bug, support
