### ISSUE TITLE
Preview: binary file contents are out of pane boundaries

### ISSUE THREAD

**Issue by militaryCoder** [vifm/vifm#847] opened 2022-11-28 18:21 UTC
I started using vifm recently and I'm very satisfied with it right now, but actually, there's some minor issue with previewing binary files.

Actually, the problem is that some lines of characters just "leak" into another pane (from which I'm selecting files to preview), like it is shown on the screenshot below.

![image](https://user-images.githubusercontent.com/55032128/204351377-ba973eaf-4f31-451e-82d1-92179f70e8e0.png)

It happens only if the directory on the other pane isn't fully occupied with filenames and it doesn't matter whether the actual directory pane is on the left side or on the right.

Looking forward to hearing from you.

**Comment by xaizek** [comment] 2022-11-28 19:02
This is essentially a duplicate of #439, so I'll close it. One of the problems is that Vifm needs to know widths of what it prints to know where to stop, but the width depends on the curses, previous characters, terminal state, locale and probably terminal itself. Your screenshot actually looks like something confused the terminal, because panes are separate curses windows and printing on one of them shouldn't affect the other.

Whitelisting characters that are printed will solve it but it will also break multibyte output, so currently "potentially confusing" characters are translated, but this doesn't solve all of it. The best idea considered is to use a heuristic to detect binary data and do a simple builtin hexdump in such case (currently you can do it youself with `fileviewer !<text/*> hexdump -C %c` or equivalent).

**Closed by xaizek** 2022-11-28 19:02 UTC

**Comment by milanglacier** [comment] 2023-08-14 03:22
Is there a way to disable `fileviewer` for binary file?

Something like:

```vim
fileviewer [ -x ] echo 'binary file cannot be previewed'
```
or something like

```vim
fileviewer [ filesize > 2M ] echo 'file is too large to be previewed'
```
