### ISSUE TITLE
Weird problems with colors

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#269] opened 2017-04-26 21:32 UTC
After recent arch linux upgrade vifm does following:

![20170426_233254_kgo](https://cloud.githubusercontent.com/assets/1045476/25458063/b5317efe-2ad8-11e7-8f5f-595ee9c742a4.png)

This happens only if I use `default` window background:

```
highlight Win cterm=none ctermfg=236 ctermbg=default
```

\- | -
---- | ----
os | `Linux tornado 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux`
vifm version | `v0.8.2-689-g6594b63d21f0`
terminal version | `rxvt-unicode (urxvt) v9.22 - released: 2015-10-11`
tmux version | `tmux master`
ncurses version | `6.0+20170401-1`
$TERM | `screen-256color` (inside tmux) / `rxvt-unicode-256color` (outside tmux)

IMO the reason might be the recent ncurses version upgrade, but recompiling vifm didn't help.

**Comment by rr-** [comment] 2017-04-26 21:35
(The reason why I'm using `default` is because the default is brighter than Xterm 255 color:

![20170426_233414_uwc](https://cloud.githubusercontent.com/assets/1045476/25458108/e2c16b68-2ad8-11e7-802f-05f9ebfe6997.png)

note how `FF` and `0F` background look grey)

**Comment by rr-** [comment] 2017-04-27 09:23
(It would be ultra-cool if we could just use RGB, but it's probably a lost cause due to ncurses not supporting these OOTB.)

**Comment by rr-** [comment] 2017-04-27 09:32
...actually the RGB idea could work if we executed `tput initc <colorid> <intensity 0...1000>{3}` before launching vifm and then restored the original colors back before exiting. Hmm

**Comment by xaizek** [comment] 2017-04-27 09:58
I think I saw similar effects once or twice under some circumstances, but can't reproduce it now (and I thought they are related to terminal or applications it was running before vifm). It looks as if color pair is not initialized, but `default` supposed to be the special one, which is predefined and thus doesn't need initialization.

By the way `E7` seems to be the brightest color in your palette.

**Comment by rr-** [comment] 2017-04-27 10:16
True, it's the `grey100` which is `0xFFFFFF`. Even though my default background is `0xFBFBFB`, I think the difference is small enough that I'll just use the `grey100` (and maybe tone down `grey100` in the `XResources` to `0xFBFBFB`).

Since you can't reproduce it and there's a simple solution to my original problem, should I close the issue?

**Comment by xaizek** [comment] 2017-04-27 10:30
Makes sense to keep the issue open in case someone else will have the same problem and also as a reminder to look into it next time it will occur. I might try to build against ncurses6, maybe it's that easy to reproduce.

**Comment by folcraed** [comment] 2017-04-27 13:32
I have the same problem with the latest Arch updates. It seems to be with ncurses, as it's affecting more than just vifm. Cmus, mc and some of my other apps are also affected, though not as obviously as vifm.


![vifm_colors](https://cloud.githubusercontent.com/assets/10911620/25485271/602ba0ee-2b2b-11e7-859a-771ed8fe784a.png)

I have a custom color config to match my vim "one-dark" theme, in which there's normally no background highlighting like you see here. I'll be filing a bug against ncurses, but I wanted to let you know there are others having the problem, in case ncurses doesn't get fixed in the near future.

BTW, thanks so very much for such a great program.

**Comment by xaizek** [comment] 2017-04-27 14:12
@folcraed, thanks a lot for the input. I just built multiple versions and the latest release to work is `ncurses-6.0-20170325`, everything after that including `ncurses-6.0-20170422` has the bug, so it was introduced in `ncurses-6.0-20170401`. I see changes related to default colors in the patch there as well, but don't see obvious reason for the bug.

**Comment by folcraed** [comment] 2017-04-27 18:11
@xaizek, I spent a while looking over ncurses (most of it way above my head) and I *think* the problem is how it's working with terminfo/termcap. I'm guessing that due to it not affecting vim, which uses it's own, and what I could make of the recent patches.

I did find this in the bug mailing list: https://lists.gnu.org/archive/html/bug-ncurses/2017-04/msg00033.html
It seems to be related. Unfortunately I've run out of time today to look further.

**Comment by xaizek** [comment] 2017-04-27 18:56
> It seems to be related.

That bug happens only after using up 256 color pairs, which won't happen right after start. I think it's a different bug.

I wouldn't spend too much time trying to find the cause unless you want to familiarize yourself with ncurses code base. It's a recent regression, maintainer must be able to find the cause quite fast. It must be in patch from [this](https://lists.gnu.org/archive/html/bug-ncurses/2017-04/msg00001.html) release as the previous one works fine.

**Comment by xaizek** [comment] 2017-04-27 21:50
I ended up spending some time anyway...

This macro in `ncurses/new_pair.h` turns any negative number of a type into maximum positive value of that type:
```c
#define LIMIT_TYPED(n,t) (t)(((t)(n) < 0) ? MAX_OF_TYPE(t) : (n))
```

`pair_content()` in `ncurses/base/lib_color.c` is now a wrapper which truncates colors to `NCURSES_COLOR_T`:
```c
NCURSES_EXPORT(int)
NCURSES_SP_NAME(pair_content) (NCURSES_SP_DCLx
			       NCURSES_PAIRS_T pair,
			       NCURSES_COLOR_T *f,
			       NCURSES_COLOR_T *b)
{
    int my_f, my_b;
    int rc = _nc_pair_content(SP_PARM, pair, &my_f, &my_b);
    if (rc == OK) {
	*f = limit_COLOR(my_f);
	*b = limit_COLOR(my_b);
    }
    return rc;
}
```

**The problem is that default colors are indicated by `-1`**.  There either must be checks like these (probably in many places)
```c
*f = (my_f != COLOR_DEFAULT) ? limit_COLOR(my_f) : my_f;
*b = (my_b != COLOR_DEFAULT) ? limit_COLOR(my_b) : my_b;
```
or `LIMIT_TYPED` is just wrong (it seems to rely on overflow, but this isn't reliable: overflow can produce positive numbers as well) and should be:
```c
#define LIMIT_TYPED(n,t) (t)(((n) > MAX_OF_TYPE(t)) ? MAX_OF_TYPE(t) : (n))
```

@folcraed, are you subscribed to their list already and will post this or should I?

**Comment by folcraed** [comment] 2017-04-28 15:22
No, I didn't subscribe @xaizek, didn't get that far as I got called away. I have now reported it, and linked this thread so the dev(s) can read your findings and reply or comment here if they wish.

Thanks for taking the time to find that. I'm not a programmer, I'd never have noticed it or known it could be a problem.

**Comment by thurstylark** [comment] 2017-04-28 17:54
So we can find it later, Here's the message that @folcraed posted: https://lists.gnu.org/archive/html/bug-ncurses/2017-04/msg00035.html

**Comment by derrickcope** [comment] 2017-04-29 08:48
After the last arch upgrade. Vifm is unusable for me. The text is underlined and flashing. After reading above, I am guessing in is a problem with ncurses.

**Comment by xaizek** [comment] 2017-04-29 10:13
@derrickcope, yes it's a bug in ncurses. It's possible to work around it in the code, but I wouldn't because it's an issue with *development version* of a third-party library. Possible workarounds:
1. Downgrading ncurses to version earlier than `ncurses-6.0-20170401`.
2. Replacing occurrences of `default` in your color scheme with some actual color (e.g. `black`).

**Comment by derrickcope** [comment] 2017-04-29 12:23
@xiazek thank you, I will adjust my color scheme accordingly.

**Comment by derrickcope** [comment] 2017-04-29 12:23
@xiazek thank you, I will adjust my color scheme accordingly.

**Comment by xaizek** [comment] 2017-04-30 09:47
New snapshot ([ncurses-6.0-20170429](https://lists.gnu.org/archive/html/bug-ncurses/2017-04/msg00037.html)) fixed the issue. Changelog says that it's the same bug as in [this report](https://lists.gnu.org/archive/html/bug-ncurses/2017-04/msg00033.html) after all (even though I don't get how it's related).

Everyone affected now just needs to wait for an upgrade of ncurses (and possibly ping maintainer of the corresponding package of your distribution).

**Closed by xaizek** 2017-04-30 09:47 UTC
Labels: ui
