### ISSUE TITLE
Finally persistent tabs and not working as for me

### ISSUE THREAD

**Issue by chelovechishko** [vifm/vifm#525] opened 2020-03-11 15:43 UTC
vifm's last git's HEAD.
after quick test.

For some reason, vifm now opens in current directory (`last-location` presented) and with two panes (i am aware about `:only`, but before switching to json it worked normally (opened at last visited directory) (even if left only one pane another one is automatically added after run the program anew)).

It	opens not `last-location`, but current dir for me (may be "history -> dir"). After simple deleting all `second ptabs` section it still creating after running vifm again. (closing via `:qall`, still only one tab (was 2 opened) (and two panes)) and no restoring of [cursor at] last selected (not visual mode) file, only a first one (no `file:` after `last-location` as i can see).
With disabled `dhistory` now, only `savedirs` (`tabs` included) and et cetera.
Or i just do something wrong? With using of non default `vifmrc`.

// vifminfo not, at least, renamed after switched to json, so it still merged every now and again (but whatever).

**Comment by xaizek** [comment] 2020-03-11 16:28
What's your `'vifminfo'`? I don't see anything like what you describe, but maybe some combination of values/options isn't accounted for.

> // vifminfo not, at least, renamed after switched to json, so it still merged every now and again (but whatever).

That's intended. This way older version of vifm can work as before and you can regenerate `vifminfo.json` easily by just deleting it. Version in `master` branch ignores the file when `vifminfo.json` exists and never merges with `vifminfo` (just reads it if `vifminfo.json` isn't there).

**Comment by xaizek** [comment] 2020-03-11 16:37
Also, just in case, try running `make check` if you haven't done that yet. There are tests for things that don't work for you.

**Comment by chelovechishko** [comment] 2020-03-11 16:38
`set vifminfo=bmarks,bookmarks,savedirs,state,tabs,tui`

**Comment by xaizek** [comment] 2020-03-11 16:49
I could reproduce only 'savedirs' bug, which remained under the check for `dhistory`. Thanks for the report, it needs a test. And `savedirs` saves only directories, if you want cursor position `dhistory` is still needed.

**Comment by chelovechishko** [comment] 2020-03-11 17:13
Excuse me for deletion after 1 day (some errors are indeed presented): https://privatebin.net/?4050b3944f488b99#Am7vXnYtxXxNZA85KFNWjxddHKfGKeJRLJGXLQ6kiwX9
Also it was done without gentoo's sed and with default options not as used "X extended-keys magic-developer -gtk -vim -vim-syntax"

**Comment by xaizek** [comment] 2020-03-11 17:58
Thanks, however all tests pass for me on Vagrant's gentoo/gentoo VM and test results just indicate an issue. But you said that `vifminfo` gets merged sometimes, which might be a sign that `vifminfo.json` is not a valid JSON file, so vifm falls back to using `vifminfo`.

This seems to check json file for validity (run it inside `~/.vifm`):

    python -c 'import json, io; json.loads(io.open("vifminfo.json", mode="r").read())'

It would be great if you could confirm that `vifminfo.json` gets broken and provide that file or just its relevant part.

**Comment by chelovechishko** [comment] 2020-03-11 18:11
> But you said that vifminfo gets merged sometimes

Nope, nope, just deleted vifminfo.json for the sake, while old file was not renamed, so it just was not expected (iirc), only this, my bad.

python's check passed successfully.

```
{"gtabs":[{"panes":[{"ptabs":[{"filters":{"invert":true,"dot":false,"manual":"","auto":""},"sorting":[12],"preview":false},{"filters":{"invert":true,"dot":false,"manual":"","auto":""},"sorting":[12],"preview":false}],"active-ptab":0},{"ptabs":[{"filters":{"invert":true,"dot":false,"manual":"","auto":""},"sorting":[12],"preview":false}],"active-ptab":0}],"active-pane":0,"splitter":{"pos":-1,"orientation":"v","expanded":true}}],"marks":{"G":{"dir":"/media/1/Games","file":"..","ts":1583941337},"M":{"dir":"/media/1/М","file":"..","ts":1583941337},"R":{"dir":"/","file":"..","ts":1583941337},"S":{"dir":"/home/username/.local/share/Steam/userdata/1111112/config","file":"..","ts":1583941337},"b":{"dir":"/home/username/Загрузки/","file":"..","ts":1583941337},"e":{"dir":"/etc","file":"..","ts":1583941337},"g":{"dir":"/home/username/git","file":"..","ts":1583941337},"h":{"dir":"/home/username/","file":"..","ts":1583941337},"l":{"dir":"/home/username/.local/share","file":"..","ts":1583941337},"m":{"dir":"/media/","file":"..","ts":1583941337},"r":{"dir":"/home/username/.t","file":"..","ts":1583941337},"t":{"dir":"/tmp","file":"..","ts":1583941337},"v":{"dir":"/home/username/.config/nvim","file":"..","ts":1583941337},"w":{"dir":"/home/username/wine_fix","file":"..","ts":1583941337}},"bmarks":{},"use-term-multiplexer":false}
```

**Comment by xaizek** [comment] 2020-03-11 22:28
I've got it:
```
$ LC_ALL=ru_RU.UTF-8 make misc
...
========================= stic v0.6 :: misc ==========================

                     16 CHECKS IN 3 TESTS FAILED
                     ---------------------------
     10954 checks :: 1077 run tests :: 0 skipped tests :: 1193 ms

======================================================================
Makefile:333: ошибка выполнения рецепта для цели «misc»
make: *** [misc] Ошибка 1
```
It's a bug in https://github.com/kgabis/parson, which is used to parse JSON. Your `vifminfo.json` contains `"active-pane":0,` where comma is interpreted as a fraction separator breaking the parsing. You can work around the issue by sticking to using the right pane :) Or using a different locale for vifm, which is obviously more reliable.

Thanks for reporting.

**Closed** 2020-03-11 23:42 UTC
Labels: bug

**Comment by chelovechishko** [comment] 2020-03-12 09:04
Oh, no-no, _you_ are welcome.
Thank you very much
