### ISSUE TITLE
sixel support

### ISSUE THREAD

**Issue by TomJansen** [vifm/vifm#419] opened 2019-03-27 14:34 UTC
Hi!
Does Vifm support sixel graphics? It is a relatively robust way to display images. I have tried to make it work in vifm with a sixel compatible terminal but unfortunately, it doesn't work, it just displays text in the preview pane.

In addition to displaying normal sixel files, a nice feature can be to convert an image with img2sixel, and then display it directly on the preview screen of vifm with vifm's filepreview command.

**Comment by xaizek** [comment] 2019-03-27 17:06
Hello.

It doesn't and I'm not sure it's possible to change this. As far as I know there is no support for it in curses, so it can only work if curses is bypassed. I know there is a function called `putp()`, but I have no idea whether it can help. In examples `putp()` is usually used without curses handling windows on the screen. Using `putp()` and windows can have conflicts.

If there exists a curses application which is capable of displaying sixel graphics, then it must be possible. I'm thinking that it might be worth asking on StackOverflow about it, Thomas Dickey (maintainer of ncurses, xterm, etc.) seems to answer quite a lot of curses-specific questions there and  probably knows the answer.

**Comment by TomJansen** [comment] 2019-03-27 17:50
Here is an answer from Thomas Dickney regarding sixel implementation in ncurses.
http://lists.gnu.org/archive/html/bug-ncurses/2016-12/msg00017.html

**Comment by xaizek** [comment] 2019-03-27 22:36
Thanks. Looks like it's not a no, but I'm not sure what "you have to see how to set aside an area on the screen which curses doesn't update" means. If it needs to not contain any curses windows, then it's a no after all. If it means that curses updates will just destroy the image, then it's fine.

I guess I just need to build xterm with sixel support and try it out.

**Comment by xaizek** [comment] 2019-04-06 15:08
I tried it earlier today and it might be doable.

The image is displayed and almost always stays on the screen (it sometimes disappears on terminal resizing). Unlike with `w3mimg`, where image might disappear too soon, sixel stays on the screen too long and might hover over completely unrelated window (for example on top of `:version`).

Also previous image isn't cleared on moving to the next file.

At least the latter issue needs to be addressed for sixel support to be useful, hovering over other windows seems to be bearable (ideally, this wouldn't happen as well, but it might not be possible to fix).

**Comment by TomJansen** [comment] 2019-04-06 15:58
>sixel stays on the screen too long and might hover over completely unrelated window (for example on top of :version

I'm just merely brainstorming here, but maybe a hack would be to replace the sixel with an empty sixel image? That is a "?" character, so a full empty sixel file would be `?\`.

**Comment by xaizek** [comment] 2019-04-06 17:05
In the case of other windows, the problem is that this needs to be done in all of them, which might be ugly (so just drawing them isn't enough, now they need this extra work first time they show up). But something like that is needed. Although, `?` might mean black and not transparent. Maybe there are other ways to erase sixel images.

**Comment by TomJansen** [comment] 2019-04-06 21:40
Maybe you can use ANSI escape codes to clear the sixel?
This small program clears the terminal screen
```
#include<stdio.h>
#define ASCII_ESC 27
int main(){
    printf("%c[2J", ASCII_ESC)
}
```
more info: http://www.climagic.org/mirrors/VT100_Escape_Codes.html

**Comment by xaizek** [comment] 2019-04-06 22:08
Thanks, I just realized that I messed up while testing if graphics erasing code works for sixel. It actually does, so this part is fine.

**Comment by xaizek** [comment] 2019-04-15 13:22
Are you using any terminal multiplexer? If you do, just vifm supporting sixel won't be enough, passing sixel data through terminal multiplexer is something to be done additionally.

**Comment by TomJansen** [comment] 2019-04-16 23:03
I do not use a terminal multiplexer, just st with sixel support patched in.
see github.com/charlesdaniels/st

**Closed** 2019-04-23 18:12 UTC
Labels: integration, ui

**Comment by xaizek** [comment] 2019-04-23 18:21
Commit closes this, but there is a caveat related to `st`. It doesn't work well there. However, it works in `xterm` and `mlterm`, so it seems to be an issue with `st`, which also loads CPU by 100% even outside vifm when `img2sixel` is used. Specifically images rarely disappear in `st`, so they end up cluttering the view.

As for image staying on the screen, it turns out `w3mimg` can leave the image visible too, so sixel doesn't differ in this regard, I just never noticed it. I might still address this, but it's not a reason to postpone merging changes for sixel.

### Example integration

### `vifmrc`

```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
         \ show-sixel %c %pw %ph %pd
```

### `$VIFM/scripts/show-sixel`

The script is for fitting image into a rect in a smart way (`img2sixel` seems to not be able to do this).

```bash
#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 filename width height"
    exit 1
fi

dim=( $(exiftool -p '$ImageWidth $ImageHeight' "$1") )

pw=$(($2*8))
ph=$(($3*14))

w=${dim[0]}
h=${dim[1]}

height=auto
width=auto
if [ $pw -lt $w ] && [ $ph -lt $h ]; then
    newh=$(echo "($h*$pw)/$w" | bc)
    neww=$(echo "($w*$ph)/$h" | bc)

    if [ $newh -le $ph ]; then
        width=$pw
    else
        height=$ph
    fi
elif [ $pw -lt $w ]; then
    width=$pw
elif [ $ph -lt $h ]; then
    height=$ph
fi

# debugging stuff
# echo pw=$pw ph=$ph
# echo w=$w h=$h
# echo neww=$neww newh=$newh
# exec echo width=$width height=$height

# account for GNU screen
if [ -n "$STY" ]; then
    popt=-P
fi

exec img2sixel $popt --width=$width --height=$height "$1"
```

**Comment by TomJansen** [comment] 2019-04-24 13:46
Awesome! Thank you so much! It is weird that in st sixels stay on the screen. But yeah, sixel is not officially supported by Suckless anyway.

**Comment by peterjschroeder** [comment] 2020-10-27 07:25
exiftool shoots out warnings on some images which causes them to be printed to screen which than causes the image to be placed outside the drawing area.

https://exiftool.org/faq.html#Q15

Adding the -m paramater fixes this.

> Commit closes this, but there is a caveat related to `st`. It doesn't work well there. However, it works in `xterm` and `mlterm`, so it seems to be an issue with `st`, which also loads CPU by 100% even outside vifm when `img2sixel` is used. Specifically images rarely disappear in `st`, so they end up cluttering the view.
> 
> As for image staying on the screen, it turns out `w3mimg` can leave the image visible too, so sixel doesn't differ in this regard, I just never noticed it. I might still address this, but it's not a reason to postpone merging changes for sixel.
> ### Example integration
> ### `vifmrc`
> 
> ```
> fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
>          \ show-sixel %c %pw %ph %pd
> ```
> 
> ### `$VIFM/scripts/show-sixel`
> 
> The script is for fitting image into a rect in a smart way (`img2sixel` seems to not be able to do this).
> 
> ```shell
> #!/bin/bash
> 
> if [ "$#" -ne 3 ]; then
>     echo "Usage: $0 filename width height"
>     exit 1
> fi
> 
> dim=( $(exiftool -p '$ImageWidth $ImageHeight' "$1") )
> 
> pw=$(($2*8))
> ph=$(($3*14))
> 
> w=${dim[0]}
> h=${dim[1]}
> 
> height=auto
> width=auto
> if [ $pw -lt $w ] && [ $ph -lt $h ]; then
>     newh=$(echo "($h*$pw)/$w" | bc)
>     neww=$(echo "($w*$ph)/$h" | bc)
> 
>     if [ $newh -le $ph ]; then
>         width=$pw
>     else
>         height=$ph
>     fi
> elif [ $pw -lt $w ]; then
>     width=$pw
> elif [ $ph -lt $h ]; then
>     height=$ph
> fi
> 
> # debugging stuff
> # echo pw=$pw ph=$ph
> # echo w=$w h=$h
> # echo neww=$neww newh=$newh
> # exec echo width=$width height=$height
> 
> # account for GNU screen
> if [ -n "$STY" ]; then
>     popt=-P
> fi
> 
> exec img2sixel $popt --width=$width --height=$height "$1"
> ```

**Comment by pglira** [comment] 2022-12-16 13:41
I'm using Konsole + vifm + sixel.

Images are shown with the script above, however, older images still don't disappear.

Did anybody find in the meanwhile a solution to this issue?

**Comment by xaizek** [comment] 2022-12-16 22:27
@pglira You can try setting `set previewoptions+=hardgraphicsclear`. It was introduced to deal with sixel clearing (#588), but don't know if it helps in Konsole.

**Comment by pglira** [comment] 2022-12-17 07:47
Thanks! Previous images get cleared now when I move to the next one. However, when I disable the file preview the last image is still there.

With file preview:
![image](https://user-images.githubusercontent.com/14214284/208231617-fdac38e5-4fee-4053-b0f1-fe4f9190116f.png)

After disabling file preview:
![image](https://user-images.githubusercontent.com/14214284/208231596-6e585b9f-5a8b-4719-8dd9-56262e3342a4.png)

Is there any solution to this issue?

**Comment by xaizek** [comment] 2022-12-17 09:39
The same clearing should be performed on switching images and on disabling preview. What's your version of Vifm?

**Comment by pglira** [comment] 2022-12-17 09:58
Should be the newest one:

```
vifm --version
Version: 0.12.1
Git info: built out of repository
Compiled at: Sep 23 2022 07:01:44

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
Without magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by pglira** [comment] 2022-12-17 10:26
I found a workaround by executing an arbitrary command together with the clear command after closing the preview panel, e.g. ``!pwd %pc clear``

**Comment by xaizek** [comment] 2022-12-17 13:43
Running `!pwd %pc clear` should be equivalent to running `!pwd` as `%pc` terminates the command.

**Comment by iambumblehead** [comment] 2024-02-08 01:21
@xaizek I hope it is not rude to "@" your name, the reason is that the issue is "closed" and I'm not sure if github will notify you of new messages added here

----------------------
I think there might be an using the above script with miller layout. Vifm here configured to use a miller layout seems to proportionally scale the images to width that is more narrow than the container and the resulting image is always smaller than desired. The image is always small, regardless of how the window is resized,
![screen-20240207-17:13](https://github.com/vifm/vifm/assets/2058705/4bd8f254-0ffa-4b2e-afd3-3f9a9bde67f4)

**Comment by xaizek** [comment] 2024-02-08 10:33
> I'm not sure if github will notify you of new messages added here

As far as I know, state of the issue doesn't affect notifications in any way.

> the resulting image is always smaller than desired

`8` and `14` in

```bash
w=$(($2*8))
ph=$(($3*14))
```

signify width and height of a single character.  Their value might just be smaller than the actual dimensions for your terminal.

**Comment by iambumblehead** [comment] 2024-03-06 07:38
@xaizek I don't routinely write bash scripts, but am attempting to write a script that can be used to preview files with vifm and would welcome any input or advice or anything at all from you https://github.com/iambumblehead/render-thumb-for.sh/

I spent the day trying to tie up loose ends to prepaare a basic first release. Here's what's good about it (I think)
 * only requires imagemagick, ffmpeg (for video and audio) and unzip (for epub)
 * currently does render svg, images, videos, fonts, audio, pdf and epub
 * release pipeline is easy to run and serves a ~5kb tar.gz

I'm currently, _trying_ to integrate it with vifm but haven't succeeded yet. Its almost midnight here and my mind not fresh. The image does appear in vifm's view panel but is super tiny https://github.com/iambumblehead/render-thumb-for.sh/pull/10

Is there way to configure the vifmrc part to send some extra data to render-for-thumb.sh, so that it may "know" the call originates from vifm and is miller three-column or regular two-column? And could maybe increase the width and height accordingly? eg, `pw=$(($2*14)); ph=$(($3*26))` How do you recommend handling this part?

**Comment by iambumblehead** [comment] 2024-03-06 08:29
lsix looks amazing, however render-thumb-for.sh may have some usefulness so will continue trying to get things working with vifm. These are things render-thumb-for.sh could still be useful for imo,
 * lsix does not by itself provide out-of-box behaviour needed for a filemanager. It does not render video, audio or epub,
 * lsix does not manage a file cache,
 * not sure about this one, but possibly lsix applies labels to all rendered images which may not be desirable,
 * lsix is intentionally not configurable through call parameters and instead the source code needs to be edited (this point is not listed as a criticism in any way, only an observation --the source code is extremely small, tidy and fun to read)

lsix detects and applies the terminal background for for transparency, imo a very cool feature

**Comment by iambumblehead** [comment] 2024-03-06 11:30
![Screenshot from 2024-03-06 03-27-29](https://github.com/vifm/vifm/assets/2058705/d9cb40f2-00b7-453e-a92e-6dd50a3fe59f)

I tried adding support for two more arguments that are multiplied on the width and the height and that seems to solve the issue, the numbers can be customized fit any sort of layout
```ini
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm,*.svg
         \ render-thumb-for.sh %c %pw %ph 30 60 %pd
```

**Comment by xaizek** [comment] 2024-03-07 09:13
@iambumblehead, looks like you've already resolved the issue, so I can only provide some feedback:
 * not sure about doing it from a bash script, but cell dimentions could be determined from terminal window resolution and number of its lines and columns
 * I get `xterm: Ignoring too-long string (692726) for mode 0x90` and no output for even small images, but that's a Sixel limitation (or rather a limitation of its handling in xterm)

**Comment by iambumblehead** [comment] 2024-03-07 19:03
@xaizek thanks for the acknowledgement. I did try to get terminal resolution rows and columns in various ways but did not succeed, maybe because I am using foot and wayland, but not sure. Some of the ways I tried were from the Dylan Araps bash bible here (neither works for me)
 * https://github.com/dylanaraps/pure-bash-bible?tab=readme-ov-file#get-the-terminal-size-in-lines-and-columns-from-a-script
 * https://github.com/dylanaraps/pure-bash-bible?tab=readme-ov-file#get-the-terminal-size-in-pixels

>  I get `xterm: Ignoring too-long string (692726) for mode 0x90`

From what I've read, xterm is one of the terminals that does render sixel images. I don't have xterm and I wish I could fix that...

**Comment by iambumblehead** [comment] 2024-03-07 20:04
A collaborator invitation is sent. Feel free to accept or ignore, its just for fun with no expectation.

**Comment by iambumblehead** [comment] 2024-03-07 20:48
@xaizek another advantage render-thumb-for.sh can provide: it could support both sixel and kitty terminal image formats.https://github.com/iambumblehead/render-thumb-for.sh/pull/14

there is an issue however, kitty will not scale images down, so they need to be preprocessed/prescaled to be exactly the right size.

**Comment by iambumblehead** [comment] 2024-03-08 00:35
I've smoke tested and seen the script run correctly now n foot, iTerm2 and kitty

**Comment by iambumblehead** [comment] 2024-03-08 02:08
@xaizek try keeping the image small as well, eg `./render-thumb-for.sh ./img.png 400 400`

**Comment by xaizek** [comment] 2024-03-08 16:15
I tried also addding these resources (the first one addresses `Ignoring too-long string` error):
```
xterm*maxStringParse: 10000000
xterm*maxGraphicSize: 10000x10000
```
but it still doesn't work reliably.  I prefer ueberzug's overlay over sixel anyway :)

**Comment by iambumblehead** [comment] 2024-03-08 19:03
I wish I had an xwindows system with xterm to improve it :| unfortunately I'm using wayland everywhere

**Comment by Mange** [comment] 2024-03-08 22:48
> I wish I had an xwindows system with xterm to improve it :| unfortunately I'm using wayland everywhere

Maybe you could run a terminal inside of XWayland? 

In terminal 1: `Xwayland :1`

In terminal 2: `DISPLAY=:1 xterm` (or some other terminal)

**Comment by iambumblehead** [comment] 2024-03-08 22:54
I haven't searched for any information about this approach, but just saw the suggestion and pasted the first line into a terminal here in Gnome
```bash
$ Xwayland :1
(EE) 
Fatal server error:
(EE) Server is already active for display 1
	If this server is no longer running, remove /tmp/.X1-lock
	and start again.
(EE) 
```

**Comment by Mange** [comment] 2024-03-09 20:19
> ```
> (EE) Server is already active for display 1
> ```

Then you can pick some other number. `Xwayland :7` and `DISPLAY=:7 xterm`

**Comment by iambumblehead** [comment] 2024-03-09 20:29
it does "work" but is extremely unpleasant. `Xwayland :7` lots of error and warning messages are printed out when running this command and a black window with no decorations appears -- the window cannot be moved or resized with mouse.

 `DISPLAY=:7 xterm` shows a little xterm window inside the black xwayland window. fonts and text look terrible and pixelated, the xterm window also is not resizable and the vifm color theme is not used when starting vifm from inside the xterm window.

It _might be_ enough to allow fixing and/or documenting solutions or xterm, thanks @Mange

**Comment by iambumblehead** [comment] 2024-03-09 20:47
![Screenshot from 2024-03-09 12-44-26](https://github.com/vifm/vifm/assets/2058705/fb46992a-d972-49ee-b0ab-b5142df0037c)

Image display at xterm is working here. xterm was started with this command and no details were added to Xresources or any other file,
```bash
DISPLAY=:7 xterm -xrm "XTerm*decTerminalID: vt340" -xrm "XTerm*numColorRegisters: 256"
```

**Comment by iambumblehead** [comment] 2024-03-10 04:37
if anyone in this thread happens to know an answer to the question here please share :) https://codeberg.org/dnkl/foot/issues/1636#issuecomment-1655511

if that question could be answered, it might be possible to make two great improvements to the script,
 1. detect the terminal and thus cell resolution to simplify the calls, rather than `render-thumb-for.sh %c %pw %ph 30 60` remove the 30 and 60 and use simpler `render-thumb-for.sh %c %pw %ph`
 2. detect the terminal's maximum allowable pixel resolution for images, in order to auto scale larger images when necessary in all terminals

**Comment by iambumblehead** [comment] 2024-03-10 06:31
sorry for the noise everyone. I think this is a bug at foot terminal emulator and it is reported upstream by me now

**Comment by FelixPehla** [comment] 2024-08-07 19:07
I've made some improvements to the script made by xaizek, notably dropping the `exiftool` dependencies, and caching the results under `~/.cache/vifm/sixel-previews`:

```bash
#!/usr/bin/bash

set -e

debug=0
if [[ "$1" == "--debug" ]]
then
    debug=1
    shift 1
fi

[[ "$debug" == "1" ]] && echo "Called with $@" >&2

if [ "$#" -ne 3 ]
then
    echo "Usage: $0 [--debug] <path_to_image> <width> <height>"
    exit 1
fi

# number of pixels for which to render the image
width=$(($2*8))
height=$(($3*14))

out=$(cat "$1" - <<<"$width $height" | sha256sum -)

checksum=${out%% *}

[[ "$debug" == "1" ]] && echo -e "\$width: $width\n\$height: $height\n\$checksum: $checksum" >&2

cache_dir="${XDG_CACHE_HOME}/vifm/sixel-previews"
mkdir -p "$cache_dir"

if [[ -f "$cache_dir/$checksum" ]]
then
    [[ "$debug" == "1" ]] && echo "File found in cache..." >&2
    exec cat "$cache_dir/$checksum"
fi

[[ "$debug" == "1" ]] && echo "File not found in cache..." >&2

mime_type="$(file --mime-type --brief -- $1)"

case "$mime_type" in

    image/jpeg|image/png)
        [[ "$debug" == "1" ]] && echo "File type: image/{jpeg,png}" >&2
        magick -- "$1" -auto-orient -strip -scale "${width}x${height}>" - | img2sixel | tee "$cache_dir/$checksum"
        ;;

    image/gif)
        [[ "$debug" == "1" ]] && echo "File type: image/gif" >&2
        exec magick -- "$1[0]" -auto-orient -strip -scale "${width}x${height}>" JPEG:- | img2sixel | tee "$cache_dir/$checksum"
        ;;

    *)
        [[ "$debug" == "1" ]] && echo "Unknown file type: $mime_type, attempting conversion" >&2
        exec magick -- "$1" -auto-orient -strip -scale "${width}x${height}>" JPEG:- | img2sixel | tee "$cache_dir/$checksum"
        ;;
esac
```

**Comment by xaizek** [comment] 2024-08-08 08:34
> dropping the `exiftool` dependencies

Well, you've essentially replaced it with ImageMagick.

> and caching the results under `~/.cache/vifm/sixel-previews`

Since this isn't done for security you might want to use `xxh*sum` instead of `sha256sum`, XXH is faster.

By the way, first invocation of `magick` lacks `exec`.

**Comment by FelixPehla** [comment] 2024-08-08 12:35
> Well, you've essentially replaced it with ImageMagick.

Yeah, but its still more performant, at least as long as I don't use any of the resource-intense functionality (like making it output sixel directly). And subsequent calls are much faster due to the cache.

```
$ time ~/.config/vifm/scripts/show-sixel xyw9kl7orn1a1.png 200 200
real	0m0,277s
user	0m0,220s
sys	0m0,055s
$ time ~/.config/vifm/scripts/show-sixel-new xyw9kl7orn1a1.png 200 200
real	0m0,082s
user	0m0,053s
sys	0m0,048s
$ time ~/.config/vifm/scripts/show-sixel-new xyw9kl7orn1a1.png 200 200
real	0m0,019s
user	0m0,002s
sys	0m0,017s
```

> Since this isn't done for security you might want to use xxh*sum instead of sha256sum, XXH is faster.

I've timed it a couple of times and at least on my machine the difference is rarely more than 3ms and I'm not sure it's worth replacing since `sha256sum` is in coreutils and can be assumed to be present on every system.

> By the way, first invocation of magick lacks exec

Well spotted, fixed.

Thanks for your comment!

**Comment by eylles** [comment] 2026-04-27 03:38
hi, took the time these days to revamp [vifm-sixel-preview](https://github.com/eylles/vifm-sixel-preview), now it makes use of the xdg thumbnail spec instead of just rendering the sixels directly, have fun!
