### ISSUE TITLE
strange nnoremap behavior

### ISSUE THREAD

**Issue by Muhkoenig** [vifm/vifm#303] opened 2018-01-17 20:00 UTC
`nnoremap <c-h> <c-w>h` is not working, but `nnoremap <c-l> <c-w>l` does.

**Comment by xaizek** [comment] 2018-01-17 21:23
Duplicate of #91.

In your environment, you need to use &lt;bs&gt; in LHS of the mapping (keeping both mappings might be a good idea):

    nnoremap <bs> <c-w>h

There is a comment about this in [documentation](https://vifm.info/vimdoc.shtml#vifm-mappings):

    Most of the time they are defined consistenly and don't cause surprises, but
    <c-h> and <bs> are treated differently in different environments (although they
    match each other all the time), that's why they correspond to different keys
    in vifm.  As a consequence, if you map <c-h> or <bs> be sure to map the other
    one to the same combination so that the mapping will work in all environments.

**Comment by xaizek** [comment] 2018-01-17 21:25
Duplicate of #91

**Closed** 2018-01-17 21:26 UTC

**Comment by Muhkoenig** [comment] 2018-01-18 06:35
I've added `nnoremap <c-h> <bs>` to my config. It still doesn't work.

**Comment by xaizek** [comment] 2018-01-18 10:37
`nnoremap <c-h> <bs>` shouldn't fix it. If you still have `nnoremap <c-h> <c-w>h`, it just redefines it. Since terminal sends `<bs>` you want to redefine it in the opposite direction and use `nmap` instead of `nnoremap`:
```
nmap <bs> <c-h>
```

**Comment by Muhkoenig** [comment] 2018-01-18 13:20
Now I understand. Thanks for the clarification. It works as expected.
