### ISSUE TITLE
Stuck in dialog window in Termux

### ISSUE THREAD

**Issue by michaellee8** [vifm/vifm#611] opened 2020-11-11 03:42 UTC
I am trying to use vifm with Termux, an android terminal emulator. However, when I try to copy a file to a destination that already exists, it gives me a dialog to choose what I want to do (Rename/Replace), but whatever I do I cannot close the dialog and therefore stuck until I kill it with tmux.

Version:
0.10.1

Steps to reproduce:
1. Install Termux from Google Play Store.
2. `pkg install vifm`
3. `mkdir -p ~/vifm-bug/test1 ~/vifm-bug/test2`
4. `touch ~/vifm-bug/test1/test.txt ~/vifm-bug/test2/test.txt`
5. Try to copy `~/vifm-bug/test1/test.txt` to ~/vifm-bug/test2` from within vifm?

Actual behavior:
Stuck forever whatever I press, Esc and Crtl+C and any key won't work

Expected behavior:
Press keys mentioned and the dialog and the paste completes.

Current workaround:
Just delete the file before overwriting.

**Comment by xaizek** [comment] 2020-11-11 12:46
Duplicate of #468

**Comment by xaizek** [comment] 2020-11-11 12:47
There was an issue on ARM and some other architectures where `char` is unsigned by default. It was fixed in 0.11.

**Comment by michaellee8** [comment] 2020-11-11 12:55
@xaizek Thank you, actually I am thinking if there is a way to get vifm without using package manager so that I can get my environment setup much easier with the latest executable. Are there any AppImage distribution for vifm like nvim does so that I can get it in restricted/legacy environment? I can contribute it if it is not existing yet.

**Comment by xaizek** [comment] 2020-11-11 13:16
Compiling Vifm from sources is quite straight-forward, you basically need `gcc` and `ncursesw-dev`.

There isn't an AppImage for Vifm yet. I think I was considering it, but then thought that something like file-manager should be installed in a regular fashion.

**Comment by michaellee8** [comment] 2020-11-11 16:27
> Compiling Vifm from sources is quite straight-forward, you basically need `gcc` and `ncursesw-dev`.
> 
> There isn't an AppImage for Vifm yet. I think I was considering it, but then thought that something like file-manager should be installed in a regular fashion.

There are some use case for AppImage. For example, I sometimes need to work on a shared-linux instance without root access. That machine don't even have the required headers so it is not possible to compile things kn it. An AppImage would be useful to bring vifm to rescue.

I am wondering if there is a way in vifm's build files (is that autoconf? I am not really familiar with that) to specify to installation directory of the binaries, for example install to ./AppDir/usr instead of /usr, these would be helpful.

**Comment by xaizek** [comment] 2020-11-11 16:47
You can specify installation root via `DESTDIR` when doing `make install`:
```bash
make DESTDIR="$PWD/AppDir" install
```

**Comment by michaellee8** [comment] 2020-11-13 07:28
@xaizek Some updates here, after dealing with Travis CI and AppImage I now I got a working genappimage.sh script and .travis.yml here https://github.com/michaellee8/vifm that can build you a appimage everytime you tag a release. However it looks like that Travis CI is running Ubuntu 16.04 which the only have libncurses-5 so it won't work on xterm-256color terminal (looks like it needs libncurses-6 to get that terminfo). Now I am trying to see if it can be obtained with apt or I will have to compile libncurses-6 manually or just switch to some newer distro to get that libncurses6

**Comment by xaizek** [comment] 2020-11-13 11:53
Looks good, thanks for the work!

AppImage doesn't contain terminfo, probably that's the reason. ncurses6 shouldn't be necessary (unless for True Colors, which aren't supported yet). For [zograscope](https://github.com/xaizek/zograscope/releases/tag/app-image) I copied terminfo inside AppImage and defined `$TERMINFO` in `AppRun`, so this shouldn't be a problem to do.

And looking at the file, I realized why I didn't build AppImage: compilation embeds absolute paths into the executable. Before providing AppImage files, I'll need to take that into account.

**Comment by michaellee8** [comment] 2020-11-13 15:05
@xaizek Thanks god I finally made it. Please refer to the notes at https://github.com/vifm/vifm/pull/615. I guess you should not merge my version of .travis.yml, you may want to change some code so that it works for your repo, those config are for my fork currently.

**Closed** 2020-11-17 17:23 UTC
