### ISSUE TITLE
Asynchronous preview

### ISSUE THREAD

**Issue by p-kolacz** [vifm/vifm#609] opened 2020-11-04 17:41 UTC
I'm using custom preview script and it's pretty fast, but for some file types it adds "hiccups" when moving through file list. I'm guessing it is because vifm waits for script to finish before displaying output and moving to the next file. It makes browsing files in millerview not optimal, especially on remote drives. Is it possible to enable asynchronous preview?

**Comment by xaizek** [comment] 2020-11-04 17:43
No, it's something that needs to be implemented. See #481.

**Comment by xaizek** [comment] 2020-12-07 17:12
Duplicate of  #481

**Comment by xaizek** [comment] 2020-12-07 17:19
Duplicate of #481

**Comment by xaizek** [comment] 2020-12-07 17:19
Please subscribe to #481 if you haven't already to keep the discussion in one place. If everything goes well, asynchronous preview of textual viewers should be available soon.

**Closed by xaizek** 2020-12-07 17:19 UTC
