### ISSUE TITLE
Possible to add space between columns?

### ISSUE THREAD

**Issue by rwtallant13** [vifm/vifm#625] opened 2020-12-14 19:04 UTC
Is it possible to add arbitrary spaces between {size} and {name}? ideally i would like to add 2 or 3 spaces between the B/K/M/G and where the filename starts for readabillity. I know i could align the size to the left but personally i would like it better with the units lined up like this.

this is my current setting and how it looks
windo set viewcolumns=10{size},-{name}..,15{atime}

![image](https://user-images.githubusercontent.com/10453230/102123429-cfb5d380-3e14-11eb-8481-988dfd1fd07d.png)

if this isnt currently possible is it expected to be added in the future or is there any sort of workaround?

**Comment by xaizek** [comment] 2020-12-14 23:47
Looks like a duplicate of #570.

In your case you could work around it by using `2{groups}` for a gap, which is empty if you don't use `'sortgroups'`.

**Closed** 2021-03-11 18:13 UTC
Labels: improvement/addition, ui
