### ISSUE TITLE
Garbled characters appear in the Chinese directory(windows-terminal)

### ISSUE THREAD

**Issue by zzx41375004** [vifm/vifm#1034] opened 2024-11-17 02:44 UTC
In windows-termianl 1.21, vifm can not work when director's name or file's name is Chinese.
![image](https://github.com/user-attachments/assets/9f21c38e-23da-45ad-9016-2d5e141dea2d)

**Comment by xaizek** [comment] 2024-11-17 11:38
CJK on Windows is problematic (at least when using PDCurses, as Vifm does).  There were [previous reports](https://q2a.vifm.info/1222/vifm-cant-render-correctly-on-windows-11?show=1223#a1223) related to Windows Terminal which were "resolved" by:
 - newer versions of Windows Terminal
 - use of WSL

I still don't know why it happens and whether there is an actual issue on Vifm side (PDCurses, really, but [I patch it](https://github.com/vifm/vifm/tree/master/patches) to make CJK work on Windows at all) given that the outcome depends on the version of WT.

Will need to give it a try again, maybe will be more lucky.  Please post problematic Chinese file names as text here so I can use them for a test in case the behaviour depends on some specific text.

**Comment by zzx41375004** [comment] 2024-11-17 13:12
Thanks, and i will help you to solve this problem(it bothered me for a long time).
By the way, this problem happens only in WT of new versions, approximately since 1.18.
In low version, like 1.15, vifm works perfectly.

## File names

工程伦理.md
数据结构.md
硕士研究生开题报告书-bak.doc
硕士研究生开题报告书.doc
笔记本信息.md
第20次全国代表大会观后感.md
算法导论中文版.pdf
随笔.md
2070276239-朱志先-软件工程.pdf

**Comment by xaizek** [comment] 2024-11-17 16:22
> By the way, this problem happens only in WT of new versions, approximately since 1.18.
> In low version, like 1.15, vifm works perfectly.

Thanks, judging by the dates:
 - 2020: [display issues](https://q2a.vifm.info/601/chinese-file-and-folder-names-are-not-correctly-displayed?show=660#c660)
 - May 2020: likely v1.0.1401.0 release
 - no display issues?
 - March 2022: [display issues](https://q2a.vifm.info/1222/vifm-cant-render-correctly-on-windows-11) (unknown WT version)
 - September 2022: v1.15.252 release (no issues)
 - September 2023: possibly v1.18.2681.0 release
 - display issues

So far it looks like a problem with WT.  Might be able to bisect it a bit to possibly extract some information.

**Comment by vodbyte** [comment] 2024-12-03 08:06
As reference, _Far Manager_ also has same problem with default setting.
![1](https://github.com/user-attachments/assets/878f3e9e-7a2f-48f4-8b82-78bc3944d7e9)

But, if check "Fullwidth-aware rendering" option in "Interface Settings", the problem will be fixed.
![2](https://github.com/user-attachments/assets/4e99f0aa-c9b7-4b88-9195-cb2339e86a37)

I hope this case can make some help.

**Comment by xaizek** [comment] 2024-12-03 13:32
Thanks, @vodbyte.  I'm yet to test it, but I likely understand what's going on: WT changed how it treats wide characters multiple times.  The patch which I apply to pdcurses pads characters that are wider than a single cell (so a Chinese character is printed as 2 characters to tell the terminal that 2 cells are used), because that makes it work with `cmd.exe` (and some versions of WT).  Apparently, this has to be an option (after testing and confirming the cause), because WT being inconsistent might change the behaviour in the future.

**Comment by xaizek** [comment] 2024-12-22 15:23
Not adding an option, because it doesn't seem to be helpful.  After dropping the padding from the output and switching to PDCurses v3.9, both new and old WT seem to display things well:

![VirtualBox_win10_22_12_2024_17_07_33](https://github.com/user-attachments/assets/9b8be3bf-6164-446e-b37d-4443a7e817fd)


Testing it in cmder, pure ConEmu, cmd.exe didn't reveal any regressions.  Quite the opposite, ConEmu now displays CJK well unless you use colors >= 16 while previously the output didn't look good regardless of the colors.

You can grab latest Windows builds from https://builds.vifm.info/ to test.

**Closed** 2024-12-22 15:22 UTC
Labels: windows, ui
